In [78]:
import pandas as pd
import matplotlib as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [81]:
df = pd.read_csv("../data/All_GPUs.csv")

In [82]:
df["Core_Speed"] = df["Core_Speed"].str.replace("MHz", '')
df['Core_Speed'] = pd.to_numeric(df['Core_Speed'], errors='coerce')
df['Core_Speed'] = df['Core_Speed'].astype("Int64")

df = df.dropna(subset=['Core_Speed'])

In [83]:


h = df.head()
c = df.corr(numeric_only=True)

display(h)
display(c)
display(df["Core_Speed"])

,Architecture,Best_Resolution,Boost_Clock,Core_Speed,DVI_Connection,Dedicated,Direct_X,DisplayPort_Connection,HDMI_Connection,Integrated,L2_Cache,Manufacturer,Max_Power,Memory,Memory_Bandwidth,Memory_Bus,Memory_Speed,Memory_Type,Name,Notebook_GPU,Open_GL,PSU,Pixel_Rate,Power_Connector,Process,ROPs,Release_Date,Release_Price,Resolution_WxH,SLI_Crossfire,Shader,TMUs,Texture_Rate,VGA_Connection
0,Tesla G92b,NaN,NaN,738,2.0,Yes,DX 10.0,NaN,0.0,No,0KB,Nvidia,141 Watts,1024 MB,64GB/sec,256 Bit,1000 MHz,GDDR3,GeForce GTS 150,No,3.3,450 Watt & 38 Amps,12 GPixel/s,None,55nm,16,\n01-Mar-2009,NaN,2560x1600,Yes,4.0,64.0,47 GTexel/s,0.0
6,R700 RV790 XT,1920 x 1080,NaN,870,1.0,Yes,DX 10.1,NaN,1.0,No,0KB,AMD,190 Watts,2048 MB,134.4GB/sec,256 Bit,1050 MHz,GDDR5,Radeon HD 4890 Sapphire Vapor-X OC 2GB Edition,No,3.3,500 Watt & 37 Amps,14 GPixel/s,2x 6-pin,55nm,16,\n13-Jul-2009,NaN,2560x1600,Yes,4.1,40.0,35 GTexel/s,1.0
11,Fermi GF110,1920 x 1080,NaN,650,2.0,Yes,DX 12.0,0.0,1.0,No,768KB,Nvidia,250 Watts,6144 MB,177.6GB/sec,384 Bit,925 MHz,GDDR5,Tesla M2090,No,4.5,600 Watt & 42 Amps,31 GPixel/s,1x 6-pin + 1x 8-pin,40nm,48,\n25-Jul-2011,NaN,2560x1600,Yes,5.0,56.0,36 GTexel/s,0.0
12,Kepler GK110,NaN,NaN,705,0.0,Yes,DX 12.0,NaN,0.0,No,1536KB,Nvidia,225 Watts,5120 MB,168GB/sec,320 Bit,1050 MHz,GDDR5,Tesla K20,No,4.5,650 Watt,NaN,None,28nm,NaN,\n01-Nov-2012,NaN,4096x2160,No,5.0,NaN,NaN,0.0
13,Kepler GK110,2560 x 1600,NaN,706,0.0,Yes,DX 12.0,NaN,0.0,No,1536KB,Nvidia,245 Watts,12288 MB,288.4GB/sec,384 Bit,1502 MHz,GDDR5,Tesla K40c,No,4.5,NaN,34 GPixel/s,None,28nm,48,\n12-Nov-2013,NaN,4096x2160,Yes,5.0,240.0,169 GTexel/s,0.0

,Core_Speed,DVI_Connection,DisplayPort_Connection,HDMI_Connection,Open_GL,Shader,TMUs,VGA_Connection
Core_Speed,1.000000,-0.034295,0.604631,0.365435,0.381442,0.269867,0.459527,-0.334777
DVI_Connection,-0.034295,1.000000,-0.169006,0.118154,0.032778,0.020874,0.178386,-0.230508
DisplayPort_Connection,0.604631,-0.169006,1.000000,0.163037,0.274134,0.208646,0.582192,-0.357923
HDMI_Connection,0.365435,0.118154,0.163037,1.000000,0.368874,0.344523,0.168618,0.003788
Open_GL,0.381442,0.032778,0.274134,0.368874,1.000000,0.942879,0.242042,-0.157606
Shader,0.269867,0.020874,0.208646,0.344523,0.942879,1.000000,0.165857,-0.127575
TMUs,0.459527,0.178386,0.582192,0.168618,0.242042,0.165857,1.000000,-0.475098
VGA_Connection,-0.334777,-0.230508,-0.357923,0.003788,-0.157606,-0.127575,-0.475098,1.000000

0        738
6        870
11       650
12       705
13       706
15      1050
17       732
18       300
20       575
21       575
24       300
26       575
27       300
28       300
29       200
31       300
35       300
36       300
38       300
39       300
40       300
41       300
43       300
44       300
46       837
47       705
49       705
51      1140
52      1127
53       902
54      1000
55      1000
56      1127
57       928
58       837
59      1000
60       837
61      1000
62       837
63       937
64       837
65       889
67       837
68       837
106      630
116      900
118      900
129      825
137      757
138      720
143      720
145      760
152      760
164      870
166     1000
168      901
170      960
171      750
172      850
174      780
175      625
176      650
178      700
179      625
180      640
181      700
182      625
183      575
184      575
185      750
186      750
190      750
191      750
192      750
193      600
194      600
195      750
196      600
199      600
200      600
201      600
202      750
203      600
206      650
207      500
208      500
210      825
211      777
216      567
229      300
230      300
231      200
232      300
234      300
236      723
237      850
239      723
240      900
241      850
243      280
244      700
246      700
247      625
248      500
249      850
250      650
251      650
252      450
253      750
259      850
261      675
262      850
265      500
266      550
269      850
271      775
273      620
274      775
275      650
276      670
277      775
278      650
280      775
281      680
283      580
284      675
285      575
286      675
287      725
288      715
289      725
290      600
291      600
292      600
293      650
294      725
295      485
296      600
297      800
298      750
299      500
300      600
301      750
302      500
303      480
304      500
313      700
316      675
317      800
318      675
319      850
320      850
321      575
322      725
323      600
324      500
325      600
326      575
327      675
328      725
329      450
330      450
331      450
332      600
333      450
334      450
335      500
336      500
337      600
338      700
339      800
340      800
341      750
342      523
343      500
344      500
345      500
351      715
352      800
353      940
354      620
355      725
356      925
359      780
360     1000
368      900
369     1000
371     1000
372      900
374      625
375      943
376     1000
377     1000
379     1000
381     1070
382     1000
383      780
384     1000
385      900
386     1000
390     1070
405      300
406      350
407      300
408      300
409      200
410      200
411      350
412      300
413      200
414      400
415      400
416      400
417      200
424      400
426      300
427      300
428      300
429      300
430      300
431      300
433      300
434      300
435      350
436      300
441      100
442      100
444      350
445      350
446      300
447      350
448      300
449      300
451      350
452      350
454      300
457      320
458      311
461      300
462      300
463      300
464      300
465      350
466      300
467      300
468      200
469      300
470      200
471      100
472      200
473      300
474      650
479      300
481      300
482      300
483      300
485      300
486      650
488      300
507      300
511      200
527      660
572      980
577      771
578      601
579      850
580      601
581      654
582      745
584      706
585      706
586      850
589      550
592      625
595      810
603      800
607      847
609      800
628      533
629      720
679      825
714      954
720      575
721      954
726      575
727      590
728      620
729      753
730      775
731      675
732      740
733      672
734      590
735      672
736      740
737      600
738      600
739      672
740      740
741      585
742      600
743      900
744      550
746      550
747      500
749     1442
750     1290
751      550
752     1480
753     1354
754      625
755      500
756     1404
760      450
761      500
766      575
767      425
768      425
769      535
770      535
771      570
773      590
774      675
775      590
776      650
777      560
778      675
779      941
780     1556
781      575
782      500
783      500
784     1029
785      606
786      876
787      936
788     1029
789     1029
791      625
794     1029
797      850
798      450
800      936
801      625
802      606
803      941
804      775
805      525
806      719
807      720
808      600
809      719
811      620
813     1029
815      606
816      598
817      598
818      601
819      835
820      745
821      900
822      710
823      753
824      500
825      850
826      625
827      650
828      660
829      660
830      625
831      660
832      672
833      625
834      800
835      800
836     1082
837      900
838      625
839      672
841      771
843      811
844      675
845      797
846      719
847      628
848      850
849      980
850      628
851      967
852      926
853      967
854      967
855      941
856      837
857      810
858      837
859      980
860      980
861      810
862      719
863      725
864      775
865      575
866      775
867      625
868      745
869     1038
870     1038
871     1038
872     1038
873      924
874      924
875      924
876      924
877      924
878     1064
879     1029
880      924
881     1029
882      738
883      993
884     1122
885      928
886      993
888      775
889      928
890      914
891     1072
892      888
893      928
894     1072
895      575
897      575
902      954
931      350
939     1018
940     1018
941     1018
942     1000
944     1000
945     1000
948     1000
949     1050
950     1000
951     1090
952     1060
953     1050
954     1055
955     1080
956     1060
957     1070
958     1100
959     1100
960     1060
961     1050
962     1070
963     1060
964     1000
965     1050
966     1010
967     1050
968     1010
969     1040
970     1025
971     1060
972     1000
973     1000
974     1050
975     1030
976     1025
977      990
978     1000
979     1010
980     1040
981     1020
982     1000
983      990
984     1020
985      980
986      970
987      970
988      980
989     1030
990      990
991      980
992      980
993      985
994      990
995      985
996      980
997     1000
998      990
999      980
1000    1000
1001     970
1002     990
1003     918
1004     980
1005     990
1006     925
1007     985
1008    1000
1009     970
1010     985
1011    1020
1012     985
1013     985
1014     970
1015     935
1016     990
1017    1020
1018    1000
1019    1000
1020     925
1021    1000
1022    1100
1023     975
1024    1000
1025     925
1026    1060
1027    1050
1028    1100
1029    1050
1030    1050
1031    1060
1032    1050
1033    1070
1034    1060
1035    1200
1036    1050
1037    1070
1038    1070
1039     730
1040    1050
1041     800
1042     830
1043    1050
1044    1000
1045    1050
1046    1000
1047    1030
1048    1080
1049    1040
1050    1040
1051    1000
1052    1040
1053    1030
1054    1080
1055    1040
1056    1040
1057    1040
1058    1040
1059    1030
1060    1000
1061    1050
1062    1050
1063    1040
1064    1000
1065    1050
1066     980
1067    1000
1068    1030
1069     947
1070     975
1071    1000
1072     975
1073    1007
1074    1000
1075     947
1076    1040
1077    1040
1078    1040
1079    1040
1080     975
1081    1000
1082     928
1083     918
1084     947
1085     918
1086     947
1087     918
1088     965
1089     945
1090     945
1091     973
1092     954
1093     918
1094     850
1095    1000
1096     973
1097     850
1099    1020
1100    1000
1101    1100
1102    1000
1103     870
1104     950
1105    1000
1106    1000
1107     880
1108    1000
1109     950
1110    1000
1112     970
1113     925
1114     850
1115     933
1116     855
1117     847
1118     950
1119     933
1120     855
1121     874
1122     850
1123     850
1125    1000
1126    1050
1127    1050
1128    1030
1129    1100
1130    1020
1131    1020
1132     827
1133    1100
1134    1060
1135    1100
1136    1030
1137    1150
1138    1030
1139    1030
1140    1030
1141    1030
1142    1100
1143    1050
1144    1030
1145    1030
1146    1050
1147    1050
1148    1000
1149    1050
1150    1000
1151     900
1152     920
1153    1030
1154     930
1155     900
1156     900
1157     950
1158     950
1159     925
1160     950
1161     900
1162    1070
1163     900
1164     930
1165     930
1166     930
1168     900
1169     900
1170    1008
1171     900
1173     930
1174    1100
1175     930
1176     900
1177    1160
1178     900
1180    1250
1181    1000
1182    1120
1183    1000
1184    1120
1185    1120
1186    1120
1187    1150
1188    1030
1189    1030
1190    1188
1192    1050
1193    1075
1194    1000
1195    1075
1196    1075
1197    1050
1198    1050
1199    1175
1200    1050
1201    1050
1202    1075
1203    1000
1204    1000
1205    1030
1206    1100
1207    1050
1208    1000
1209    1000
1210    1075
1211    1075
1212    1000
1213    1160
1214    1100
1215    1188
1216    1188
1217    1150
1218    1188
1219    1175
1220    1160
1221    1100
1222    1100
1223    1100
1224    1120
1225    1120
1226    1208
1227    1208
1228    1120
1229    1120
1230    1120
1231    1120
1232    1120
1233    1120
1234    1120
1235    1120
1236    1120
1237    1120
1238    1120
1239    1120
1240    1120
1241    1120
1242    1000
1243    1120
1244    1120
1245    1050
1246    1120
1247     950
1248    1120
1249    1100
1250    1000
1251    1050
1252     950
1253    1000
1254     950
1255    1020
1256    1000
1257     800
1258     800
1259     800
1260    1020
1261    1000
1262     950
1263    1000
1264    1050
1265    1000
1266    1000
1267    1120
1268    1000
1269    1000
1270    1120
1271    1120
1272    1120
1273    1120
1274    1120
1275    1120
1276    1120
1277    1120
1278    1120
1279    1120
1280    1120
1281    1120
1282    1120
1283    1120
1284    1120
1285    1120
1286     926
1287    1120
1288     926
1289    1000
1290    1050
1291     926
1292     926
1293    1000
1294    1000
1295    1050
1296    1000
1297    1000
1298    1000
1299    1000
1300    1000
1301    1000
1302     730
1303    1050
1304     730
1305    1000
1306     730
1307     730
1308     730
1309     730
1310     730
1311     730
1312     926
1313     750
1314    1121
1315    1143
1316     926
1317     926
1318     926
1319     926
1320     926
1321     926
1322     926
1323     926
1324     926
1325     926
1326    1090
1327    1090
1329     926
1330    1090
1331    1090
1332     926
1333    1090
1334    1090
1335    1090
1337    1090
1340    1090
1343    1090
1344    1090
1347    1090
1349     750
1351     760
1352    1090
1353     730
1354     730
1355     780
1356     730
1357     770
1358     730
1359     730
1360     775
1361     875
1362     625
1363     625
1364     625
1365     625
1366     625
1367     625
1368     625
1369     650
1370     625
1371     625
1374     625
1377     825
1378     650
1389    1090
1456    1175
1457    1175
1459    1175
1460    1175
1461    1175
1462    1175
1463    1175
1464    1175
1465    1175
1466    1175
1467    1175
1468    1180
1469    1175
1470    1180
1471    1180
1472    1175
1473    1175
1474    1180
1475    1175
1476    1175
1477    1180
1478    1175
1479    1175
1480    1175
1481    1175
1482    1175
1483    1180
1484    1175
1485    1175
1486    1175
1487    1175
1488    1175
1489    1175
1490    1175
1491    1175
1492    1090
1493    1090
1494     400
1550     350
1552     350
1554     350
1555     400
1559     650
1561     850
1565     350
1566     850
1567     350
1571     350
1583     350
1585     350
1586     350
1587     350
1588     650
1589     350
1590     650
1591     650
1592     850
1593     650
1594     850
1595     850
1597     350
1598     850
1599     350
1600     350
1602     350
1605     350
1606     350
1607     350
1609     350
1612     350
1613     350
1614     350
1625     350
1630     950
1631     925
1632     950
1634     830
1636    1000
1637     550
1640     574
1643     902
1644     773
1646     902
1647     706
1648     667
1649     706
1650     667
1651     876
1652     876
1653     876
1655     574
1658     625
1659     706
1662     738
1664     625
1665     513
1666     612
1667     600
1668     550
1670     675
1671     600
1672     600
1673     600
1675     650
1682     650
1712     513
1714     575
1717     650
1718     513
1720     576
1721     600
1722     540
1723     675
1724     675
1726     540
1727     540
1728     540
1729     540
1730     640
1731     540
1732     460
1733     450
1735     520
1736     520
1738     520
1740     450
1741     450
1744     567
1749     550
1756     830
1757     830
1759     900
1760     880
1761     880
1762     880
1763     940
1764     880
1765     880
1766     880
1767     880
1768     890
1769     800
1770     800
1771     800
1772     800
1773     800
1774     800
1775     800
1777     840
1778     870
1779     925
1781     900
1782     900
1783     930
1784     920
1785     800
1786     900
1787     900
1788     940
1789     915
1790     900
1791     915
1792     775
1793     800
1794     800
1795     775
1796     900
1797     820
1798     775
1799     860
1800     800
1801     820
1802     820
1803     775
1804     820
1805     790
1807     820
1808     775
1809     840
1810     840
1811     900
1812     850
1813     840
1814     850
1815     850
1816     800
1817     850
1819     850
1820     850
1821     700
1822     700
1823     700
1824     700
1825     700
1826     700
1827     700
1828     800
1829     820
1830     740
1831     800
1832     800
1833     800
1834     800
1835     800
1836     800
1837     800
1838     800
1839     800
1840     800
1841     800
1842     800
1843     650
1844     650
1845     650
1846     800
1847     650
1848     810
1849     650
1850     650
1851     650
1852     650
1853     650
1854     650
1855     625
1856     625
1857     625
1858     675
1859     625
1860     625
1861     750
1862     750
1863     625
1864     625
1865     650
1867     650
1869     625
1870     650
1886     625
1892     900
1898     850
1899     850
1900     765
1901     760
1902     735
1904     725
1905     850
1907     860
1909     765
1911     725
1912     850
1913     765
1914     725
1915     850
1916     850
1917     875
1918     850
1919     725
1921     775
1923     800
1925     850
1926     950
1929     775
1930     775
1935     775
1942     925
1944     955
1946    1050
1948     950
1949    1100
1950    1050
1951    1080
1952    1010
1953    1100
1954     925
1955    1000
1956    1050
1957    1050
1958    1000
1959    1050
1960    1000
1961    1070
1962    1000
1963    1070
1964    1000
1965     925
1966    1050
1967     925
1968     925
1969    1050
1970    1050
1971     925
1972     900
1973     900
1974     900
1975     950
1976     880
1977     880
1978     860
1979     850
1980     880
1982     830
1983     880
1984     925
1985     800
1986     900
1987     800
1988     860
1989     860
1990     900
1991     900
1992     800
1993     850
1994     850
1995     800
1996     850
1997     900
1998     925
1999     925
2000     800
2001     925
2002     925
2003    1000
2004    1050
2005    1050
2006    1100
2007    1000
2008    1050
2009    1150
2010    1100
2011    1050
2012    1100
2013    1030
2014    1100
2015    1100
2016    1100
2017    1000
2018    1010
2019    1000
2020    1100
2021    1000
2022    1050
2023    1000
2024    1000
2025    1000
2026     860
2027     975
2028     975
2029     860
2030    1000
2031    1000
2032     900
2033     860
2034     920
2035    1000
2036     950
2037     900
2038    1000
2039    1000
2040     975
2041     900
2042     900
2043     860
2044     860
2045     975
2046    1000
2047     860
2048     870
2049     860
2050     910
2051     860
2052     860
2053     860
2054     860
2066    1000
2067    1095
2069    1000
2070    1000
2071    1150
2073    1150
2074    1100
2075    1000
2076    1100
2077    1000
2078    1000
2079    1000
2080    1150
2081    1000
2082    1020
2083    1050
2084    1100
2085    1120
2086    1020
2087    1000
2088    1120
2089    1020
2090    1000
2091     800
2092    1000
2093     800
2094     800
2095     800
2096     800
2097    1000
2098     800
2099     800
2100     800
2101     800
2102     830
2103     800
2104     900
2105     800
2106     830
2107     880
2108     850
2109     800
2110     800
2111     800
2112     900
2113     800
2114     820
2115     800
2116     800
2117     800
2118     840
2119     800
2122     900
2123     800
2124     800
2125     650
2126     800
2127     650
2128     650
2129     750
2131     650
2133     625
2134     900
2135    1000
2137     925
2139     800
2140    1000
2141    1000
2142     625
2143     750
2144     650
2145     730
2153     874
2155     607
2156     576
2157     701
2160     600
2162     915
2166    1006
2167     915
2168     915
2169    1216
2170    1110
2171    1006
2172    1006
2173     993
2174    1084
2175    1058
2176    1006
2177    1006
2178    1084
2179    1006
2180    1480
2182    1683
2183    1645
2184    1607
2185    1771
2186    1480
2187     576
2188    1480
2189    1569
2190    1480
2191    1480
2192    1506
2193    1569
2194    1480
2195    1480
2196    1480
2197    1506
2198    1480
2199    1531
2200    1480
2201    1607
2202    1480
2203    1569
2204    1569
2205    1480
2206    1480
2207    1531
2208    1480
2209    1480
2210    1607
2211    1480
2212    1506
2213    1607
2214    1480
2215    1518
2216    1480
2217    1556
2218    1556
2219    1480
2220    1480
2221    1480
2222    1480
2223    1569
2224    1480
2225    1594
2226    1582
2227    1480
2228    1480
2229    1708
2230    1607
2231    1607
2232    1607
2233    1607
2234    1607
2235    1708
2236    1607
2237    1645
2238    1657
2239    1480
2240    1708
2241    1632
2242    1607
2243    1607
2244    1695
2245    1721
2246    1607
2247    1708
2248    1607
2249    1480
2250    1607
2251    1632
2252    1784
2253    1708
2254    1607
2255    1607
2256    1506
2257    1607
2258    1506
2259    1607
2260    1670
2261    1607
2262    1632
2263    1607
2264    1657
2265    1607
2266    1632
2267    1556
2268    1506
2269    1569
2270    1695
2271    1556
2272    1582
2273    1531
2274    1506
2275    1506
2276    1657
2277    1594
2278    1506
2279    1518
2280    1670
2281    1594
2282    1506
2283    1506
2284    1506
2285    1657
2286    1657
2287    1506
2288    1620
2289    1531
2290    1531
2291    1506
2292    1506
2293    1582
2294    1620
2295    1506
2296    1506
2298    1556
2300    1506
2302    1569
2303    1518
2307    1544
2308    1518
2309    1544
2312    1556
2313    1632
2314    1569
2315    1569
2316    1620
2317    1544
2318    1506
2320    1531
2322    1556
2323    1594
2327    1518
2329    1620
2332    1617
2333    1607
2335    1506
2336    1506
2337    1645
2338    1637
2339    1570
2341    1506
2342    1506
2344    1506
2347    1354
2348    1392
2349    1303
2350    1366
2351    1341
2352    1290
2353    1316
2354    1303
2355    1290
2356    1290
2357    1290
2358    1379
2359    1354
2360    1290
2361    1354
2362    1341
2363    1316
2364    1392
2365    1290
2366    1290
2367    1290
2368    1341
2369    1303
2370    1366
2371    1290
2372    1379
2373    1392
2374    1366
2375    1354
2376    1290
2377    1354
2378    1290
2379    1290
2380    1290
2381    1354
2382    1404
2383    1379
2384    1404
2385    1442
2386    1366
2387    1354
2388    1354
2389    1404
2390    1379
2391    1366
2392    1354
2393    1417
2394    1442
2395    1417
2396    1354
2397    1354
2398    1430
2399    1354
2400    1442
2401    1417
2402    1110
2403    1354
2405    1442
2406    1100
2407    1071
2408    1006
2409    1006
2410    1137
2411    1150
2412    1110
2413    1202
2414    1110
2415    1084
2416    1006
2417    1071
2418    1097
2419    1110
2420    1058
2421    1084
2422    1084
2423    1111